apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ready-demo
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ready-demo
    spec:
      containers:
      - name: ready-demo
        image: demo
        ports:
        - containerPort: 80
          name: 
        imagePullPolicy: Always

