apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ready-demo
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ready-demo
    spec:
      containers:
      - name: ready-demo
        image: sviera91/ready-demo:v0.3
        ports:
        - containerPort: 80
          name: 
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ready-demo
spec:
  loadBalancerIP: 104.211.17.146
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: ready-demo